# Generated by Django 2.2.6 on 2019-11-07 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20191026_2241'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='users',
            new_name='users1',
        ),
    ]
