# Generated by Django 2.2.6 on 2019-11-07 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20191107_2324'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='users1',
            new_name='box',
        ),
    ]
